version: '3.8'

services:

#
# Database
#
  db_mysql:
    image: mysql:8.0.28
    container_name: dbsql
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: public
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - vo_db:/etc/mysql/mysql.conf.d
    restart: always
    networks:
      - overlay

#
# phpmyadmin
#
  phpmyadmin:
    image: phpmyadmin:5.1.3-apache
    container_name: phpmyadmin
    ports: 
      - 8080:80 
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db_mysql
    volumes:
      - vo_phpadmin:/etc/phpmyadmin/config.user.inc.php
    restart: always
    networks:
      - overlay

volumes:
  vo_db:
  vo_phpadmin:

networks:
  overlay: